<h2>Accordion</h2>
<div id="accordion">
    <div>
        <h3 tabindex="0" aria-expanded="true" role="tab" class="ui-accordion-header ui-helper-reset ui-state-active ui-corner-all">
            <span class="ui-icon ui-icon-triangle-1-s"></span>
            <a tabindex="-1" href="#" title="First slide" class="tooltip">First</a>
        </h3>
        <div role="tabpanel" style="height: 181px;" class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom ui-accordion-content-active">
            Praesent augue urna, vehicula sed sollicitudin quis, dignissim nec est. Quisque dignissim lorem at metus vehicula ut feugiat eros vestibulum. Suspendisse ultrices, massa luctus aliquam faucibus, sem quam fermentum nisl, non posuere quam nunc vel tellus.
        </div>
    </div>
    <div>
        <h3 tabindex="-1" aria-expanded="false" role="tab" class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all">
            <span class="ui-icon ui-icon-triangle-1-e"></span>
            <a tabindex="-1" href="#" title="Second slide" class="tooltip">Second</a>
        </h3>
        <div role="tabpanel" style="height: 181px; display: none;" class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom">
            Sed sem elit, porttitor quis vestibulum ut, euismod id purus. Praesent vulputate dolor vel nisi mattis sollicitudin. Curabitur placerat quam at sem tempor ac sodales nunc dapibus. Nullam mi purus, adipiscing in facilisis sed, posuere ut ipsum.
        </div>
    </div>
    <div>
        <h3 tabindex="-1" aria-expanded="false" role="tab" class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all">
            <span class="ui-icon ui-icon-triangle-1-e"></span>
            <a tabindex="-1" href="#" title="Third slide" class="tooltip">Third</a>
        </h3>
        <div role="tabpanel" style="height: 181px; display: none;" class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom">
            Praesent augue urna, vehicula sed sollicitudin quis, dignissim nec est. Quisque dignissim lorem at metus vehicula ut feugiat eros vestibulum. Suspendisse ultrices, massa luctus aliquam faucibus, sem quam fermentum nisl, non posuere quam nunc vel tellus.
        </div>
    </div>
</div>

<h2>Sortable Dialogs</h2>
<div class="sort ui-sortable">
    <div class="box ui-widget ui-widget-content ui-corner-all portlet ui-helper-clearfix">
        <div class="portlet-header ui-widget-header ui-corner-all">
            <span class="ui-icon ui-icon-circle-arrow-s"></span>Sortable 1
        </div>
        <div class="portlet-content">
            <p>This is a sortable dialog. Lorem ipsum dolor sit amet</p>
        </div>
    </div>
    <div class="box ui-widget ui-widget-content ui-corner-all portlet ui-helper-clearfix">
        <div class="portlet-header ui-widget-header ui-corner-all">
            <span class="ui-icon ui-icon-circle-arrow-s"></span>Sortable 2
        </div>
        <div class="portlet-content">
            <p>This is a sortable dialog. Praesent augue urna, vehicula sed sollicitudin quis, dignissim nec est.</p>
        </div>
    </div>
    <div class="box ui-widget ui-widget-content ui-corner-all portlet ui-helper-clearfix">
        <div class="portlet-header ui-widget-header ui-corner-all">
            <span class="ui-icon ui-icon-circle-arrow-s"></span>Sortable 3
        </div>
        <div class="portlet-content">
            <p>This is a sortable dialog. Praesent augue urna, vehicula sed sollicitudin quis, dignissim nec est.</p>
        </div>
    </div>
</div>

<h2>Lists / Navigation</h2>
<ul>
    <li><a href="#">Lorem Ipsum</a></li>
    <li><a href="#">Artificial Intelligence</a></li>
    <li><a href="#">jQuery Power</a>
        <ul>
            <li><a href="#">Lorem Ipsum</a></li>
            <li><a href="#">Artificial Intelligence</a></li>
            <li><a href="#">Lorem Ipsum</a>
                <ul>
                    <li><a href="#">Lorem Ipsum</a></li>
                    <li><a href="#">Artificial Intelligence</a></li>
                    <li><a href="#">Lorem Ipsum</a></li>
                    <li class="last"><a href="#">Artificial Intelligence</a></li>
                </ul>
            </li>
            <li class="last"><a href="#">Artificial Intelligence</a></li>
        </ul>
    </li>
    <li><a href="">Another category</a></li>
</ul>

<h2>Statistics</h2>
<p><b>Modules:</b> 1</p>
<p><b>Users:</b> 1</p>
<p><b>Visitors:</b> 2</p>