<h1>An error occurred</h1>
<h2><?php echo $this->message; ?></h2>

<?php
    if('development' == APP_ENV):
?>
    <h3>Exception information</h3>
    <p>
        <b>Message:</b> <?php echo $this->exception->getMessage(); ?>
        <b>Message:</b> <?php echo $this->message; ?>
    </p>

    <h3>Stack trace:</h3>
    <pre><?php echo $this->exception->getTraceAsString(); ?></pre>

    <h3>Request Parameters:</h3>
    <pre><?php var_dump($this->request->getParams()); ?></pre>
<?php
    endif;
?>
    <h1><?php echo $this->title?></h1>
    <?php if ($this->message): ?>
        <p>The following error occurred:</p>
        <pre>
        <?php echo $this->message ?>
        </pre>
    <?php endif; ?>